<?php

namespace AppBundle\Repository;

/**
 * TestDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestDateRepository extends \Doctrine\ORM\EntityRepository
{
}
